apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: halo-theme-hydro-minim
spec:
  displayName: 氢·简
  author:
    name: Lywq
    website: https://github.com/halo-dev
  description: Hydro-Minim，氢系列首款极简 Halo 主题，以轻快、留白和流畅动效呈现内容。
  logo: /themes/halo-theme-hydro-minim/assets/brand/hydro-minim-mark.svg
  homepage: https://github.com/halo-dev
  repo: https://github.com/halo-dev
  issues: https://github.com/halo-dev
  settingName: "halo-theme-hydro-minim-setting"
  configMapName: "halo-theme-hydro-minim-configMap"
  version: 1.0.0
  requires: ">=2.20.0"
  license:
    - name: "GPL-3.0"
      url: "https://www.gnu.org/licenses/gpl-3.0.html"
